name: github-actions demo

on: 
  push:
    branches: 
      - main
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  schedule:
   - cron: '15 6 * * 0'
  workflow_dispatch:
  
jobs: 
  Build:
    runs-on: unbuntu-latest
    steps:
      - run: |
         echo "🎉 The job was triggered by event: ${{ github.event_name }}"
         echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."
        name: print
        
      - uses: actions/checkout@3.30
      
      - name: List files in repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
      
    
  
    
  
